### ISSUE TITLE
Poderia me ajudar?

### ISSUE THREAD

**Issue by feliperafaelbarbosa** [Marcelo391/marcelo391.github.io#1]
Olá **Marcelo391**, sou novo no github, você poderia me ajudar com algum material que me auxilie na hospedagem de site no github?

**Comment by Marcelo391** [comment]
Boa tarde.
Você precisa criar um repositório com o seguinte nome:  **_nomedousuario.github.io_**

Por exemplo o nome do meu repositório ficou: **marcelo391.github.io**
No seu caso será **FRafaelBarbosa.github.io**

Depois é só colocar nesse repositório os arquivos do seu site. 
O edereço do seu site será: **https://nomedousuario.github.io/**

Links úteis: 
https://medium.com/@manoelangelo/hospedando-seu-site-no-github-4fde46578a6b
https://blog.paulagrangeiro.com.br/hospedando-sites-gratuitamente-com-o-github-pages-284aa643db14

**Comment by feliperafaelbarbosa** [comment]
Muito obrigado amigo!

**Comment by Marcelo391** [comment]
Por nada ! Fico feliz em ajudar !
